["Rings of Ascension"]
	#The amount of hearts that Max Health's ring gives you.
	#Range: 0 ~ 400
	ringHealthHearts = 5
	#The cooldown in seconds of the Ring of Undying
	#Range: > 0
	ringUndyingCooldown = 600

["Enable/Disable Rings"]
	ringWaterWalking = true
	ringMagnetism = true
	ringSponge = true
	ringNightVision = true
	ringRegeneration = false
	ringPoisonResistance = true
	ringStrength = true
	ringGrowth = true
	ringInvisibility = false
	ringWaterBreathing = true
	ringWither = false
	ringDolphin = true
	ringKnockbackResistance = true
	ringHungerless = false
	ringFireResistance = true
	ringExperience = true
	ringMining = true
	ringHealth = false
	ringSlowResistance = true
	ringJumpBoost = true
	ringLuck = true
	ringSpeed = true
	ringUndying = false
	ringSlowFalling = true
	ringFlight = false

["Rings Amplifier"]

	#Sets the amplifier of the effect given by the ring. Example:
	#0 = Fire Resistance I
	#1 = Fire Resistance II
	["Rings Amplifier".Amplifiers]
		#Range: 0 ~ 255
		ringAmplifierSlowFalling = 0
		#Range: 0 ~ 255
		ringAmplifierJumpBoost = 0
		#Range: 0 ~ 255
		ringAmplifierDolphin = 0
		#Range: 0 ~ 255
		ringAmplifierInvisibility = 0
		#Range: 0 ~ 255
		ringAmplifierWaterBreathing = 1
		#Range: 0 ~ 255
		ringAmplifierLuck = 1
		#Range: 0 ~ 255
		ringAmplifierRegeneration = 0
		#Range: 0 ~ 255
		ringAmplifierFireResistance = 1
		#Range: 0 ~ 255
		ringAmplifierStrength = 0
		#Range: 0 ~ 255
		ringAmplifierMining = 0
		#Range: 0 ~ 255
		ringAmplifierSpeed = 0
		#Range: 0 ~ 255
		ringAmplifierNightVision = 0

["Rings Tier"]

	#Sets the Tier of the rings. Higher tier rings are more difficult to find.
	#0 = Common
	#1 = Rare
	#2 = Epic
	#3 = Legendary
	["Rings Tier".Tiers]
		ringTierWaterBreathing = 3
		ringTierKnockbackResistance = 1
		ringTierNightVision = 0
		ringTierPoisonResistance = 2
		ringTierSlowFalling = 1
		ringTierMagnetism = 2
		ringTierSponge = 1
		ringTierSpeed = 2
		ringTierWither = 3
		ringTierHealth = 3
		ringTierLuck = 3
		ringTierRegeneration = 3
		ringTierDolphin = 1
		ringTierWaterWalking = 1
		ringTierInvisibility = 3
		ringTierGrowth = 1
		ringTierMining = 3
		ringTierUndying = 3
		ringTierFireResistance = 2
		ringTierStrength = 2
		ringTierHungerless = 3
		ringTierJumpBoost = 1
		ringTierSlowResistance = 3
		ringTierFlight = 3
		ringTierExperience = 0

["Rings Loot"]
	#The maximum number of rings that can be found inside a single chest.
	ringMaxLoot = 1
	#The minimum number of rings that can be found inside a single chest.
	ringMinLoot = 0

["Rings Loot Chests"]
	#Generate rings in woodland mansion chests
	ringWoodlandChests = true
	#Generate rings in village toolsmith chests
	ringToolsmithChests = false
	#Generate rings in dungeon chests
	ringDungeonChests = false
	#Generate rings in pillager outpost chests
	ringPillagerChests = true
	#Generate rings in village armorer chests
	ringArmorerChests = false
	#Generate rings in abandoned mineshaft chests
	ringMineshaftChests = false
	#Generate rings in desert pyramid chests
	ringPyramidChests = false
	#Generate rings in end city chests
	ringEndCityChests = true
	#Generate rings in stronghold library chests
	ringStrongholdChests = false
	#Generate rings in village weaponsmith chests
	ringWeaponsmithChests = false
	#Generate rings in buried treasure chests
	ringBuriedTreasureChests = false
	#Generate rings in igloo chests
	ringIglooChests = false
	#Generate rings in nether bridge chests
	ringNetherChests = true
	#Generate rings in spawn bonus chests
	ringBonusChests = false
	#Generate rings in shipwreck treasure chests
	ringShipwreckChests = false
	#Generate rings in jungle temple chests
	ringJungleChests = true

